# Generated by Django 3.0.4 on 2020-03-20 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
