# Generated by Django 2.1.15 on 2020-03-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200327_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(help_text="We know this is for a remote position, but applicants still want to know where a potential employer's HQ is located.", max_length=64),
        ),
    ]
