# Generated by Django 2.1.15 on 2020-03-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200327_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_link',
            field=models.CharField(max_length=256),
        ),
    ]
