# Generated by Django 2.1.15 on 2020-03-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200327_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="This won't be shared with users, rather this is so our team can get in touch with you should we have any issues.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
