# Generated by Django 2.1.15 on 2020-03-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200327_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
